# Docker Compose file Reference (https://docs.docker.com/compose/compose-file/)

version: '3.6'

# Define services
services:
  # App Service
  svcgtw:
    build: ./svcgtw
    image: sap-svcgtw
    container_name: svcgtw
    ports: 
        - "9090:9090"
    restart: unless-stopped
    networks:
        - default

  svc-call:
    # Configuration for building the docker image for the service
    build: ./svc-call
    image: sapgorfc
    container_name: sapgorfc
    ports:
      - "8089:8089" # Forward the exposed port 50051 on the container to port 50051 on the host machine
    restart: unless-stopped
    networks: # Networks to join (Services on the same network can communicate with each other using their name)
      - default
    env_file:
      - ./svc-call/.env
